# Cloudflare Workers/Pages Configuration
# This file is used for local development and deployment configuration
# More info: https://developers.cloudflare.com/workers/wrangler/configuration/

name = "settlements"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
pages_build_output_dir = "./dist"

# KV Namespaces for sessions (if needed)
# Uncomment and add your KV namespace ID from Cloudflare Dashboard
# [[kv_namespaces]]
# binding = "SESSION"
# id = "your-kv-namespace-id-here"
# preview_id = "your-preview-kv-namespace-id-here"

# Environment variables (for local development only)
# Production secrets should be set in Cloudflare Dashboard or GitHub Secrets
[vars]
# Add non-sensitive environment variables here

# For development, use .dev.vars file (gitignored) for secrets:
# PUBLIC_SUPABASE_URL=https://your-project.supabase.co
# PUBLIC_SUPABASE_ANON_KEY=your-anon-key

