name: E2E Tests

on:
  push:
    branches: [master, main, develop]
  pull_request:
    branches: [master, main, develop]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase local instance
        run: supabase start

      - name: Get Supabase credentials
        id: supabase
        run: |
          echo "PUBLIC_SUPABASE_URL=$(supabase status -o env | grep API_URL | cut -d '=' -f2)" >> $GITHUB_OUTPUT
          echo "PUBLIC_SUPABASE_ANON_KEY=$(supabase status -o env | grep ANON_KEY | cut -d '=' -f2)" >> $GITHUB_OUTPUT
          echo "SUPABASE_SERVICE_ROLE_KEY=$(supabase status -o env | grep SERVICE_ROLE_KEY | cut -d '=' -f2)" >> $GITHUB_OUTPUT

      - name: Create .env.e2e file
        run: |
          cat > .env.e2e << EOL
          PUBLIC_SUPABASE_URL=${{ steps.supabase.outputs.PUBLIC_SUPABASE_URL }}
          PUBLIC_SUPABASE_ANON_KEY=${{ steps.supabase.outputs.PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY=${{ steps.supabase.outputs.SUPABASE_SERVICE_ROLE_KEY }}
          BASE_URL=http://localhost:4322
          EOL

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        run: npm run test:e2e
        env:
          CI: true

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-results
          path: playwright-results/
          retention-days: 30

      - name: Stop Supabase
        if: always()
        run: supabase stop

